version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
install:
    runtime-versions:
      nodejs: 10

artifacts:
  files:
    - index.html
    - favicon.favicon
    - Foerde.Thor.CV.pdf
    - styles/main.css
    - images/*
